### ISSUE TITLE
Doesn't work with latest api-client-python (0.6.0+)

### ISSUE THREAD

**Issue by bennettaur** [gleanwork/langchain-glean#16]
Glean's [api-client-python](https://github.com/gleanwork/api-client-python/tree/v0.6.0) changed the import path for importing the SDK
from 
```python
 from glean import Glean
```
to

```python
from glean.api_client import Glean
```

starting in v0.6.0 And this library just defines the dependency `glean-api-client>=0.4.2` so fresh installs break like so:

```bash
  File "/Users/mbennett/dev/ws/id25-agentic-domains/.venv/lib/python3.13/site-packages/langchain_glean/__init__.py", line 3, in <module>
    from langchain_glean.chat_models import ChatGlean, ChatGleanAgent
  File "/Users/mbennett/dev/ws/id25-agentic-domains/.venv/lib/python3.13/site-packages/langchain_glean/chat_models/__init__.py", line 3, in <module>
    from langchain_glean.chat_models.agent_chat import ChatGleanAgent
  File "/Users/mbennett/dev/ws/id25-agentic-domains/.venv/lib/python3.13/site-packages/langchain_glean/chat_models/agent_chat.py", line 3, in <module>
    from glean import Glean, errors, models
ImportError: cannot import name 'Glean' from 'glean' (unknown location)
```

**Comment by rwjblue-glean** [comment]
Oof! Sorry about that!! Will take a look and see about getting a new release out.
